config/routes.rb
Worldcup::Application.routes.draw do
  
  

  resources :players do
   collection do
     put 'activate'
     get 'bowlers'
     get 'batsmen'
     get 'wicketkeepers'
   end
  end

  resources :coaches do
    member do
      get 'activate'
    end
  end
  
  controller :session do 
    get 'login' => :new 
    post 'login' => :create
    delete 'logout' => :destroy
  end 
  
  get "session/new"
  get "session/create"
  get "session/destroy"
    
   resources :batsman
   resources :wicketkeeper
   resources :bowler
   
   match '/activate/:activation_code' => 'coaches#activate'

  root :to => "session#new"

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new

  end

  def create
    if coach = Coach.authenticate(params[:email], params[:encrypted_password])
      @status = Coach.find_by_email(params[:email])
      if @status.activated_at.blank?
        redirect_to login_path, :alert => "Your Status is not active"
      else
        session[:coach_id] = coach.id
        redirect_to players_path
      end  
    else
      redirect_to login_path, :alert => "Invalid user id or password"
    end
  end

  def destroy
    session[:coach_id] = nil
    redirect_to session_new_path, :alert => "Logged out"
  end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.erb
<% if flash[:alert]%>
<%= flash[:alert]%>
<%end%>
<div>
	<%= form_tag do %>
	<fieldset>
		<legend>Please Log In</legend>
		<div> 
			<label for="name">E-Mail:</label>
			<%= text_field_tag :email, params[:email] %>
		</div>
		<div>
			<label for="password">Password:</label>
			<%= password_field_tag :encrypted_password, params[:encrypted_password] %>
		</div>
		<div>
		<%= submit_tag "Login" %>
		<%= link_to "New Coach",new_coach_path %>
	</div>
	</fieldset>
	<% end %>	
<div>