config/routes.rb
Worldcup::Application.routes.draw do
  
  

  resources :players do
   collection do
     put 'activate'
     get 'bowlers'
     get 'batsmen'
     get 'wicketkeepers'
   end
  end

  resources :coaches do
    member do
      get 'activate'
    end
  end
  
  controller :session do 
    get 'login' => :new 
    post 'login' => :create
    delete 'logout' => :destroy
  end 
  
  get "session/new"
  get "session/create"
  get "session/destroy"
    
   resources :batsman
   resources :wicketkeeper
   resources :bowler
   
   match '/activate/:activation_code' => 'coaches#activate'

  root :to => "session#new"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/coach.rb
require 'digest/sha2'
class Coach < ActiveRecord::Base

  has_many :players
  validates :name,:team_name, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validates :password , :presence => true, :confirmation => true, :if => Proc.new{|user| user.validate_password == true}

  attr_accessor :password, :validate_password

  def self.authenticate(email, password)
    if user = find_by_email(email)
      if user.encrypted_password == Digest::SHA2.hexdigest(password)
        user
      end
    end
  end

  def password=(password)
    @password =password
    if password.present?
      self.encrypted_password = Digest::SHA2.hexdigest(password)
    end
  end

  private

  def password_must_be_present
    errors.add(:password, "Missing password") unless encrypted_password?
  end


end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def index
    @allteams =  Coach.all(:select => "team_name,activated_at")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @coaches }
    end
  end

  def show
    @coach = Coach.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @coach }
    end
  end

  def new
    @coach = Coach.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @coach }
    end
  end

  def edit
    @coach = Coach.find(params[:id])
  end

  def create

    @coach = Coach.new(params[:coach])
    @coach.validate_password = true
    @coach.activation_code = rand(99999).to_s
    respond_to do |format|
      if  @coach.save
        Accountactivation.sendlink(@coach,request.host_with_port).deliver
        format.html { redirect_to(login_path, :alert => 'Coach was successfully created. and check your mail for activate your account') }
        format.xml  { render :xml => @coach, :status => :created, :location => @coach }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @coach.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @coach = Coach.find(params[:id])
    respond_to do |format|
      if @coach.update_attributes(params[:coach])
        format.html { redirect_to(@coach, :notice => 'Coach was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @coach.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @coach = Coach.find(params[:id])
    @coach.destroy

    respond_to do |format|
      format.html { redirect_to(coaches_url) }
      format.xml  { head :ok }
    end
  end

  def activate
    @coach = Coach.find_by_activation_code(params[:activation_code])
    if  @coach.update_attributes(:activated_at => Time.now, :activation_code => nil)
      render(:text => "Your account is updates sucessfully")
    else
      render(:text => "fail in update")
    end
  end
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/_form.html.erb
<%= form_for(@coach) do |f| %>
<% if @coach.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@coach.errors.count, "error") %> prohibited this coach from being saved:</h2>

	<ul>
		<% @coach.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field"> 
	<%= f.label :name%>
	<%= f.text_field :name %>
</div>
<div class="field"> 
	<%= f.label :email %>
	<%= f.text_field :email %>
</div>
<div class="field"> 
	<%= f.label :password ,'Password'%>
	<%= f.password_field :password %>
</div>
<div class="field"> 
	<%= f.label :password_confirmation ,'Confirm Password'%>
	<%= f.password_field :password_confirmation %>
</div>
<div class="field"> 
	<%= f.label :team_name_confirmation ,'Team Name'%>
	<%= f.text_field :team_name %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/coaches/edit.html.erb
<h1>Editing coach</h1>

<%= render 'form' %>

<%= link_to 'Show', @coach %> |
<%= link_to 'Back', coaches_path %>

app/views/coaches/index.html.erb
<h1>Listing Teams of WorlCup</h1>
<%if flash[:alert]%>
	<%= flash[:alert]%>
	<%end%>
	<table>
		<tr>
			<th>Team Name</th>
			<th></th>
			<th></th>
		</tr>

		<%  @allteams.each do |team| %>

		<tr>
			<td><%= team.team_name%></td>
			<%if team.activated_at.blank?%>
			<td>InActive</td>
			<%else%>
			<td class= "green">Active</td>
			<%end%>
		</tr>
		<% end %>
	</table>

	<br />

app/views/coaches/new.html.erb
<h1>New coach</h1>

<%= render 'form' %>

app/views/coaches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to(coaches_url, coaches_path)%>
<%= link_to 'Edit', edit_coach_path(@coach) %> |
<%= link_to 'Back', coaches_path %>