config/routes.rb
Worldcup::Application.routes.draw do
  
  

  resources :players do
   collection do
     put 'activate'
     get 'bowlers'
     get 'batsmen'
     get 'wicketkeepers'
   end
  end

  resources :coaches do
    member do
      get 'activate'
    end
  end
  
  controller :session do 
    get 'login' => :new 
    post 'login' => :create
    delete 'logout' => :destroy
  end 
  
  get "session/new"
  get "session/create"
  get "session/destroy"
    
   resources :batsman
   resources :wicketkeeper
   resources :bowler
   
   match '/activate/:activation_code' => 'coaches#activate'

  root :to => "session#new"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/player.rb
class Player < ActiveRecord::Base
  PLAYER_TYPES = ["Batsman","Bowler","WicketKeeper"]
  belongs_to :coach
  validates :email ,:type, :presence => true
  validate :addplayers_validation
  #before_create :playerscount,:checkbowler,:checkwicketkeeper,:checkbatsman
   def addplayers_validation
  self.errors[:base] << "Every coach can add only 15 players" if Player.count(:conditions => {:coach_id => coach_id}) >= 15  
  self.errors[:base] << "Every coach can add maximum 6 bowler" if type== "Bowler" && Bowler.count(:conditions => {:coach_id => coach_id}) > 5 
  self.errors[:base] << "Every coach can add maximum 2 WicketKeeper" if type== "WicketKeeper" && WicketKeeper.count(:conditions => {:coach_id => coach_id}) > 1
  self.errors[:base] << "Every coach can add maximum 7 Batsman" if type== "Batsman" && Batsman.count(:conditions => {:coach_id => coach_id}) > 6
   end
  # def playerscount
  #     totalplayers = Player.count(:conditions => {:coach_id => coach_id})
  #     if totalplayers >= 15 
  #       self.errors[:base] = 'Every coach can add only 15 players'
  #       return false
  #     end
  #   end
  # 
  #   def checkbowler
  #     if type== "Bowler" && Bowler.count(:conditions => {:coach_id => coach_id}) > 5
  #       self.errors[:base] = "u Cant add more than 6 bowler"
  #       return false
  #     end
  #   end
  # 
  #   def checkwicketkeeper
  #     if type== "WicketKeeper" && WicketKeeper.count(:conditions => {:coach_id => coach_id}) > 1
  #       self.errors[:base] = "u Cant add more than 2 wicketkeeper"
  #       return false
  #     end
  #   end
  # 
  #   def checkbatsman
  #     if type== "Batsman" && Batsman.count(:conditions => {:coach_id => coach_id}) > 6
  #       self.errors[:base] = "u Cant add more than 7 Batsman"
  #       return false
  #     end
  #   end

  def self.activate(hash={})
    a = Array.new
    hash["status"].collect do |k,v|
      if v[:status] =="1"
        a.push(k)
      end
    end
    b= Player.count(:conditions => {:type => "Bowler" , :id => a})
    bat= Player.count(:conditions => {:type => "Batsman" , :id => a})
    w= Player.count(:conditions => {:type => "WicketKeeper" , :id => a})
    if b < 3 || bat < 5 || w< 1 || (b+bat+w) >11
      return false
    else
      return true
    end  
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_filter :authorize
  def index
    @players = Player.all(:conditions => {:coach_id => coach_id})
    @totalteammember = Player.count(:conditions => {:coach_id => coach_id, :status => 1})
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @players }
    end
  end


  def show
    @player = Player.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @player }
    end
  end

  def new
    @player = Player.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @player }
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def create
    coach = coach_id 
    @player = Player.new(params[:player].merge(:coach_id => coach_id))
    @player.type=params[:player][:type]
   
    respond_to do |format|
            if @player.save
              format.html { redirect_to(@player, :notice => 'Player was successfully created.') }
              format.xml  { render :xml => @player, :status => :created, :location => @player }
            else
              format.html { render :action => "new" }
              format.xml  { render :xml => @player.errors, :status => :unprocessable_entity }
            end
          end
  end


  def update
    @player = Player.find(params[:id])
    respond_to do |format|
      if @player.update_attributes(params[:player])
        p @player
        format.html { redirect_to(player_path(@player), :notice => 'Player was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @player.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    respond_to do |format|
      format.html { redirect_to(players_url) }
      format.xml  { head :ok }
    end
  end


  def activate
    if Player.activate(params)
      Player.update(params[:status].keys, params[:status].values)
      flash[:notice] = 'Selected Players are active now.'
      redirect_to :action => "index"
    else
      flash[:notice] = 'Selected Players cannot be made active. Please select alteast 3 bowler, 5 batsmr and 1 wicketkeeper'
      redirect_to :action => "index"
    end

  end

  def batsmen
    @players = Batsman.all(:include => [:coach])
    render 'players'
  end

  def bowlers
    @players = Bowler.all(:include => [:coach])
    render 'players'
  end

  def wicketkeepers
    @players = WicketKeeper.all(:include => [:coach])
    render 'players'
  end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
	<% if @player.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

		<ul>
			<% @player.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div class="field"> 
		<%= f.label :type %>
		<%= f.select :type, Player::PLAYER_TYPES, :prompt => 'Select a Player Type' %>
	</div>
	<div class="field"> 
		<%#= f.label :status %>
		<%#= f.check_box :status %>
	</div>
	<%= f.submit  %> 
	<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<% if @totalteammember < 11 %>
    <p> Team Can't be Play Because atleast maximum team player should b 15 but not more than 15 and 11 team player must b active for playing game </p>
 <% else %>
     <p>Team Satisfy all conditions of selection process so it can play game</p>

<%end%>
<%=flash[:notice]%>
<h1>Listing players</h1>
	<%= form_tag(activate_players_path) do %>

<table>
	<tr>
		<th>Player Name</th>
		<th>Player Type</th>
		<th>Status</th>
		<th></th>
	</tr>

	<% @players.each do |player| %>
	 <%= fields_for "status[]", player do |statusfiled| %>

	<tr>
		
		<td><%= player.email%></td>
		<td><%= player.type%></td>
		<td><%= player.status %></td>
		<td><%= statusfiled.check_box :status %></td>
		<%#= check_box_tag "status", player.status, player.status  %>
	</tr>
		   <% end %>	
	<% end %>
</table>
<br/>
<%= submit_tag "Change Status"%>

<br />
<% end %>

<%= link_to 'New Player', new_player_path %>
<%= link_to 'View Team Name', coaches_path%>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/players.html.erb
<h1>Listing <%= @players.first[:type].pluralize %></h1>
<table>
	<tr>
		<th>Player Name </th>
		<th>Team Name</th>

	</tr>
	<% @players.each do |player| %>

	<tr>
		<td><%= player.email %></td>
		<td> <%= player.coach.team_name %></td>
		<% end %>
	</table>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<span><b>Email:</b></span>
	<span><%= @player.email %></span>
</p>
<p>
	<span><b>Type:</b></span>
	<span><%= @player.type %></span>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>